"""
Plantilla de actividades del Plan de Trabajo Anual SG-SST 2026.
Basado en el documento PL-SST-02, versión 1, fecha 1/02/2026.

Cada actividad incluye:
- ciclo: I_PLANEAR | II_HACER | III_VERIFICAR | IV_ACTUAR
- categoria: RECURSOS | GESTION_INTEGRAL | GESTION_SALUD | GESTION_PELIGROS |
             GESTION_AMENAZAS | VERIFICACION | MEJORAMIENTO
- estandar: código del estándar (ej. "1.1.1")
- descripcion: descripción del estándar
- frecuencia: mensual, trimestral, semestral, anual, etc.
- responsable: responsable predeterminado
- recurso_financiero: True/False
- recurso_tecnico: True/False
- meses_programados: lista de meses (1-12) donde la actividad está programada (P)
"""


NOMBRE_MESES = [
    "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
]

TODOS_LOS_MESES = list(range(1, 13))


def get_plantilla_actividades(año: int) -> list:
    """
    Retorna la lista de actividades estándar del Plan de Trabajo Anual SG-SST.
    Los meses programados (P) están basados en el cronograma del PDF.
    """
    actividades = [

        # =====================================================================
        # I. PLANEAR — RECURSOS (Estándares 1.1.x, 1.2.x)
        # =====================================================================
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.1",
            "descripcion": "Designación del Responsable del SG SST de la entidad",
            "frecuencia": "Mensual",
            "responsable": "Alta Dirección",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.2",
            "descripcion": "Asignar y socializar las responsabilidades de SST a todos los niveles de la organización",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.3",
            "descripcion": "Elaboración, Revisión y Aprobación del Presupuesto Anual",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección / Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.4",
            "descripcion": "Seguimiento a la Afiliación de los trabajadores al Sistema de seguridad social en salud, pensión y riesgos",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4, 5, 7, 9, 10],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.5",
            "descripcion": "Identificar trabajos de alto riesgo según el decreto 2090 del 2003",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4, 5, 7, 10],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.6",
            "descripcion": "Conformación del COPASST y Capacitar al Comité Paritario de SST según lo establece la normatividad colombiana",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.7",
            "descripcion": "Reuniones COPASST y capacitaciones",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.8",
            "descripcion": "Conformación del Comité de Convivencia Laboral y Capacitar en temas, según la normatividad legal vigente",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.1.8",
            "descripcion": "Reuniones del Comité de Convivencia Laboral",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4, 5, 7, 10],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.2.1",
            "descripcion": "Diseño Programa de Capacitación",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.2.2",
            "descripcion": "Inducción del SGSST",
            "frecuencia": "Semestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "RECURSOS",
            "estandar": "1.2.3",
            "descripcion": "Capacitación 50 Horas SG SST con la ARL o SENA",
            "frecuencia": "Cada 2 años",
            "responsable": "Profesional de apoyo de SST, COPASST, ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [5],
        },

        # =====================================================================
        # I. PLANEAR — GESTIÓN INTEGRAL DEL SISTEMA (Estándares 2.x.x)
        # =====================================================================
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.1.1",
            "descripcion": "Revisión de la Política SST: actualización anual",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / Alta Dirección / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.1.1",
            "descripcion": "Firma de la política actual",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.1.1",
            "descripcion": "Publicación y Socialización de la Política",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.2.1",
            "descripcion": "Revisar y Actualizar los Objetivos del SG SST",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia / Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.3.1",
            "descripcion": "Evaluación Inicial",
            "frecuencia": "Anual",
            "responsable": "Profesional SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.4.1",
            "descripcion": "Plan de Trabajo anual",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / Alta Dirección / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.4.1",
            "descripcion": "Manual SG SST",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / Alta Dirección / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.5.1",
            "descripcion": "Revisión, actualización de la Documentación, Procedimientos, Instructivos, formatos del SGSST",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.5.1",
            "descripcion": "Conservación de la documentación del Sistema de Gestión de Seguridad y Salud en el Trabajo, como lo exige la normatividad",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.6.1",
            "descripcion": "Rendición de cuentas, Responsabilidades asignadas",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia / Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [2],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.6.1",
            "descripcion": "Responsabilidades del SG SST en los perfiles de cargo",
            "frecuencia": "Anual",
            "responsable": "Todos los trabajadores",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [12],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.7.1",
            "descripcion": "Actualización de la Matriz Legal",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 4, 7, 10],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.8.1",
            "descripcion": "Seguimiento y cierre a las comunicaciones (Reportes de actos y condiciones inseguras) que se realizan por parte de los trabajadores de la entidad",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.9.1",
            "descripcion": "Procedimiento de Compras, actualización y seguimiento",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia / Responsable del SG SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [6, 7],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.10.1",
            "descripcion": "Evaluación de proveedores y contratistas",
            "frecuencia": "Mensual",
            "responsable": "Alta Dirección: Gerencia / Responsable del SG SST",
            "recurso_financiero": False,
            "recurso_tecnico": False,
            "meses_programados": [1],
        },
        {
            "ciclo": "I_PLANEAR",
            "categoria": "GESTION_INTEGRAL",
            "estandar": "2.11.1",
            "descripcion": "Diseñar y documentar el procedimiento de gestión del Cambio y documentar los cambios",
            "frecuencia": "Semestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3, 5, 7, 9],
        },

        # =====================================================================
        # II. HACER — GESTIÓN DE LA SALUD (Estándares 3.x.x)
        # =====================================================================
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.1",
            "descripcion": "Actualización del Perfil Sociodemográfico",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa / IPS",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.2",
            "descripcion": "Solicitar Diagnóstico de Condiciones de Salud suministrados por la IPS de los últimos exámenes ejecutados",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / IPS",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [5],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.2",
            "descripcion": "Establecer Programa de promoción y prevención o PVE - Según como lo recomiende el médico ocupacional en el diagnóstico de condiciones de salud",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [6],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.3",
            "descripcion": "Solicitar a IPS, el Profesiograma de acuerdo a los cargos de la entidad",
            "frecuencia": "Actualización cuando se generan nuevos cargos y riesgos",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.4",
            "descripcion": "Exámenes Médicos periódicos ocupacionales para el personal de planta de la entidad y si es contratista Exigirlo al contratista",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / IPS",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.5",
            "descripcion": "Solicitud carta de Guarda y custodia de las Historias clínicas a la IPS",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / IPS",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.6",
            "descripcion": "Entrega al Trabajador de las recomendaciones y restricciones resultantes de las evaluaciones médicas ocupacionales",
            "frecuencia": "Cada vez que se generen las respectivas recomendaciones",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [5],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.7",
            "descripcion": "Programas de PyP, estilos de vida y trabajo saludable, seguimiento y cierre",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / ARL / IPS",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [6, 8, 12],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.8",
            "descripcion": "Campañas de Orden y Aseo, Suministro de agua potable",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4, 7, 9, 11],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.1.9",
            "descripcion": "Verificar la Disposición de Residuos en todos los centros de trabajo de la entidad",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4, 6, 7, 9, 10, 12],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.2.1",
            "descripcion": "Revisar y Actualizar (de ser necesario) el Mecanismos para el Reporte de incidentes y Accidentes de Trabajo y enfermedades laborales",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [7],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.2.2",
            "descripcion": "Verificar que se Reporte e Investiguen todos los Incidentes, Accidentes de Trabajo, enfermedades laborales",
            "frecuencia": "Cada vez que se presenten",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.2.3",
            "descripcion": "Reportes de Mortalidad y Ausentismo, Incidencia y Prevalencia",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.1",
            "descripcion": "Medición de la frecuencia de los accidentes de trabajo",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.2",
            "descripcion": "Medición de la severidad de los accidentes de trabajo",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.3",
            "descripcion": "Proporción de accidentes mortales",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.4",
            "descripcion": "Medición de la prevalencia de enfermedad laboral",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.5",
            "descripcion": "Medición de la incidencia de enfermedad laboral",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_SALUD",
            "estandar": "3.3.6",
            "descripcion": "Medición del ausentismo por causa médica",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },

        # =====================================================================
        # II. HACER — GESTIÓN DE PELIGROS Y RIESGOS (Estándares 4.x.x)
        # =====================================================================
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.1.1/4.1.2",
            "descripcion": "Actualización de la Matriz de Identificación de Peligros, Evaluación y Valoración de Riesgos de SST anual o cuando se presente un accidente laboral (tener en cuenta la participación de los trabajadores)",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST / COPASST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.1.3",
            "descripcion": "Identificación de sustancias catalogadas como carcinógenas o toxicidad aguda",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [8],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.1.4",
            "descripcion": "Mediciones ambientales",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [8],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.1",
            "descripcion": "Matriz de Jerarquización de los Riesgos, programas de gestión",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": False,
            "recurso_tecnico": False,
            "meses_programados": [3, 6, 9, 12],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.1",
            "descripcion": "Aplicación de Baterías para el Riesgo psicosocial",
            "frecuencia": "Anual",
            "responsable": "IPS / Psicólogo especialista en SST",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [8],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.1",
            "descripcion": "Plan de acción Propuestas Riesgo Psicosocial",
            "frecuencia": "Semestral",
            "responsable": "Responsable del SG SST / Psicóloga",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 7],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.1",
            "descripcion": "Inspecciones Ergonómicas a Puestos de Trabajo",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [9],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.2",
            "descripcion": "Verificación de aplicación de medidas de prevención y control por parte de los trabajadores",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [6],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.3",
            "descripcion": "Elaboración de procedimientos, instructivos, fichas, protocolos",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.3",
            "descripcion": "Implementar Plan Estratégico de Seguridad Vial",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección: Gerencia",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [7],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.4",
            "descripcion": "Implementar programa de inspecciones",
            "frecuencia": "Bimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2, 4, 6, 8, 10],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.4",
            "descripcion": "Realización de inspecciones sistemáticas a las instalaciones, maquinaria o equipos con la participación del COPASST",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.4",
            "descripcion": "Inspección Locativa en los centros de trabajo de la entidad",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3, 6, 9, 12],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.5",
            "descripcion": "Mantenimiento periódico de instalaciones, equipos, máquinas, herramientas",
            "frecuencia": "Bimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4, 6, 8, 10, 12],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.6",
            "descripcion": "Elementos de Protección Personal - matriz de EPP por riesgo y cargo y capacitación",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_PELIGROS",
            "estandar": "4.2.6",
            "descripcion": "Verificar la entrega de los EPP - Ver Matriz de EPP por Cargo",
            "frecuencia": "Cuatrimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [4, 8, 12],
        },

        # =====================================================================
        # II. HACER — GESTIÓN DE AMENAZAS (Estándar 5.x.x)
        # =====================================================================
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_AMENAZAS",
            "estandar": "5.1.1",
            "descripcion": "Diseño y verificación del Plan Operativo de Emergencias (vulnerabilidad, amenazas) en todos los centros de trabajo de la entidad",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [1, 2],
        },
        {
            "ciclo": "II_HACER",
            "categoria": "GESTION_AMENAZAS",
            "estandar": "5.1.2",
            "descripcion": "Capacitación entrenamiento a las Brigadas, conformación (Resolución 0256 de 2014) en todos los centros de trabajo de la entidad",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [7],
        },

        # =====================================================================
        # III. VERIFICAR — VERIFICACIÓN DEL SG-SST (Estándares 6.x.x)
        # =====================================================================
        {
            "ciclo": "III_VERIFICAR",
            "categoria": "VERIFICACION",
            "estandar": "6.1.1",
            "descripcion": "Seguimiento a indicadores de acuerdo a la estructura, proceso y resultados del SG SST",
            "frecuencia": "Trimestral",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [3, 6, 9, 12],
        },
        {
            "ciclo": "III_VERIFICAR",
            "categoria": "VERIFICACION",
            "estandar": "6.1.2/6.1.3",
            "descripcion": "Auditoría Interna - planeada con el COPASST",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [10],
        },
        {
            "ciclo": "III_VERIFICAR",
            "categoria": "VERIFICACION",
            "estandar": "6.1.4",
            "descripcion": "Revisión por la Dirección",
            "frecuencia": "Anual",
            "responsable": "Alta Dirección",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [12],
        },

        # =====================================================================
        # IV. ACTUAR — MEJORAMIENTO (Estándares 7.x.x)
        # =====================================================================
        {
            "ciclo": "IV_ACTUAR",
            "categoria": "MEJORAMIENTO",
            "estandar": "7.1.1",
            "descripcion": "Definición de acciones preventivas y correctivas con base en resultados del SG-SST",
            "frecuencia": "Mensual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "IV_ACTUAR",
            "categoria": "MEJORAMIENTO",
            "estandar": "7.1.2/7.1.3/7.1.4",
            "descripcion": "Acciones de mejora con base en revisión de la alta dirección, investigaciones de accidentes e incidentes de trabajo y enfermedades laborales, incluyendo recomendaciones de la ARL",
            "frecuencia": "Cada vez que se presenten",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "IV_ACTUAR",
            "categoria": "MEJORAMIENTO",
            "estandar": "7.1.4",
            "descripcion": "Plan de mejora Investigación de Incidentes, Accidentes de Trabajo, enfermedades laborales, incluyendo recomendaciones de la ARL",
            "frecuencia": "Cada vez que se presenten",
            "responsable": "Responsable del SG SST / ARL",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "costo": 20000,
            "meses_programados": TODOS_LOS_MESES,
        },
        {
            "ciclo": "IV_ACTUAR",
            "categoria": "MEJORAMIENTO",
            "estandar": "7.1.4",
            "descripcion": "Reporte de Evaluación de estándares mínimos y planes de acción",
            "frecuencia": "Anual",
            "responsable": "Responsable del SG SST de la Empresa",
            "recurso_financiero": True,
            "recurso_tecnico": False,
            "meses_programados": [6],
        },
    ]

    # Asignar orden y retornar
    for idx, act in enumerate(actividades):
        act["orden"] = idx
        act.setdefault("costo", None)

    return actividades
