"""update_worker_vacations_table_structure

Revision ID: 03e987fcd84c
Revises: 7561cd51fec8
Create Date: 2025-09-26 01:34:22.417949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e987fcd84c'
down_revision = '7561cd51fec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar nuevas columnas
    op.add_column('worker_vacations', sa.Column('days_requested', sa.Integer(), nullable=True))
    op.add_column('worker_vacations', sa.Column('comments', sa.Text(), nullable=True))
    
    # Migrar datos existentes
    op.execute("UPDATE worker_vacations SET days_requested = days")
    op.execute("UPDATE worker_vacations SET comments = reason")
    
    # Hacer las nuevas columnas no nulas después de migrar los datos
    op.alter_column('worker_vacations', 'days_requested', nullable=False)
    
    # Eliminar constraint de foreign key y columnas antiguas
    op.drop_constraint('worker_vacations_requested_by_fkey', 'worker_vacations', type_='foreignkey')
    op.drop_column('worker_vacations', 'reason')
    op.drop_column('worker_vacations', 'rejection_reason')
    op.drop_column('worker_vacations', 'days')
    op.drop_column('worker_vacations', 'is_active')
    op.drop_column('worker_vacations', 'requested_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_vacations', sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('worker_vacations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('worker_vacations', sa.Column('days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('worker_vacations', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('worker_vacations', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key('worker_vacations_requested_by_fkey', 'worker_vacations', 'users', ['requested_by'], ['id'])
    op.drop_column('worker_vacations', 'comments')
    op.drop_column('worker_vacations', 'days_requested')
    # ### end Alembic commands ###