"""Add ENFERMEDAD_LEVE to EventType enum

Revision ID: 068250d6256f
Revises: d41b1ce2e9a0
Create Date: 2025-09-25 18:52:35.138866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068250d6256f'
down_revision = 'd41b1ce2e9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new value to EventType enum
    op.execute("ALTER TYPE eventtype ADD VALUE 'ENFERMEDAD LEVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # You would need to recreate the enum type if you want to remove the value
    pass
    # ### end Alembic commands ###