"""add_fecha_de_ingreso_to_worker

Revision ID: 08ce17d054a5
Revises: 30d1676cc33b
Create Date: 2025-08-12 18:17:55.667737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08ce17d054a5'
down_revision = '30d1676cc33b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('fecha_de_ingreso', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'fecha_de_ingreso')
    # ### end Alembic commands ###