"""create_missing_programas_table

Revision ID: 0d3b7dcdb7ea
Revises: 106e441ffcc4
Create Date: 2025-10-21 14:29:07.421580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3b7dcdb7ea'
down_revision = '106e441ffcc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create programas table
    op.create_table('programas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_programa', sa.String(length=200), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    
    op.execute('DROP INDEX IF EXISTS idx_course_materials_module_id')
    op.execute('DROP INDEX IF EXISTS idx_course_modules_course_id')
    op.execute('DROP INDEX IF EXISTS idx_enrollments_course_id')
    op.execute('DROP INDEX IF EXISTS idx_enrollments_created_at')
    op.execute('DROP INDEX IF EXISTS idx_enrollments_user_course')
    op.execute('DROP INDEX IF EXISTS idx_enrollments_user_id')
    op.execute('DROP INDEX IF EXISTS idx_notifications_created_at')
    op.execute('DROP INDEX IF EXISTS idx_notifications_user_id')
    op.execute('DROP INDEX IF EXISTS idx_occupational_exams_exam_date')
    op.execute('DROP INDEX IF EXISTS idx_occupational_exams_worker_id')
    op.execute('DROP INDEX IF EXISTS idx_survey_questions_survey_id')
    op.execute('DROP INDEX IF EXISTS idx_surveys_course_id')
    op.execute('DROP INDEX IF EXISTS idx_surveys_created_at')
    op.execute('DROP INDEX IF EXISTS idx_surveys_status')
    op.execute('DROP INDEX IF EXISTS idx_surveys_status_course')
    op.execute('DROP INDEX IF EXISTS idx_user_material_progress_material_id')
    op.execute('DROP INDEX IF EXISTS idx_user_material_progress_status')
    op.execute('DROP INDEX IF EXISTS idx_user_material_progress_user_id')
    op.execute('DROP INDEX IF EXISTS idx_user_material_progress_user_material')
    op.execute('DROP INDEX IF EXISTS idx_user_module_progress_module_id')
    op.execute('DROP INDEX IF EXISTS idx_user_module_progress_status')
    op.execute('DROP INDEX IF EXISTS idx_user_module_progress_user_id')
    op.execute('DROP INDEX IF EXISTS idx_user_module_progress_user_module')
    op.execute('DROP INDEX IF EXISTS idx_user_survey_answers_question_id')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_created_at')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_status')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_survey_id')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_survey_status')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_user_id')
    op.execute('DROP INDEX IF EXISTS idx_user_surveys_user_status')
    op.execute('DROP INDEX IF EXISTS idx_users_active_role')
    op.execute('DROP INDEX IF EXISTS idx_users_document_number')
    op.execute('DROP INDEX IF EXISTS idx_users_is_active')
    op.execute('DROP INDEX IF EXISTS idx_users_role')
    op.execute('DROP INDEX IF EXISTS idx_workers_document_number')
    op.execute('DROP INDEX IF EXISTS idx_workers_is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop programas table
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    
    op.create_index('idx_workers_is_active', 'workers', ['is_active'], unique=False)
    op.create_index('idx_workers_document_number', 'workers', ['document_number'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_document_number', 'users', ['document_number'], unique=False)
    op.create_index('idx_users_active_role', 'users', ['is_active', 'role'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_user_surveys_user_status', 'user_surveys', ['user_id', 'status'], unique=False)
    op.create_index('idx_user_surveys_user_id', 'user_surveys', ['user_id'], unique=False)
    op.create_index('idx_user_surveys_survey_status', 'user_surveys', ['survey_id', 'status'], unique=False)
    op.create_index('idx_user_surveys_survey_id', 'user_surveys', ['survey_id'], unique=False)
    op.create_index('idx_user_surveys_status', 'user_surveys', ['status'], unique=False)
    op.create_index('idx_user_surveys_created_at', 'user_surveys', ['created_at'], unique=False)
    op.create_index('idx_user_survey_answers_question_id', 'user_survey_answers', ['question_id'], unique=False)
    op.create_index('idx_user_module_progress_user_module', 'user_module_progress', ['user_id', 'module_id'], unique=False)
    op.create_index('idx_user_module_progress_user_id', 'user_module_progress', ['user_id'], unique=False)
    op.create_index('idx_user_module_progress_status', 'user_module_progress', ['status'], unique=False)
    op.create_index('idx_user_module_progress_module_id', 'user_module_progress', ['module_id'], unique=False)
    op.create_index('idx_user_material_progress_user_material', 'user_material_progress', ['user_id', 'material_id'], unique=False)
    op.create_index('idx_user_material_progress_user_id', 'user_material_progress', ['user_id'], unique=False)
    op.create_index('idx_user_material_progress_status', 'user_material_progress', ['status'], unique=False)
    op.create_index('idx_user_material_progress_material_id', 'user_material_progress', ['material_id'], unique=False)
    op.create_index('idx_surveys_status_course', 'surveys', ['status', 'course_id'], unique=False)
    op.create_index('idx_surveys_status', 'surveys', ['status'], unique=False)
    op.create_index('idx_surveys_created_at', 'surveys', ['created_at'], unique=False)
    op.create_index('idx_surveys_course_id', 'surveys', ['course_id'], unique=False)
    op.create_index('idx_survey_questions_survey_id', 'survey_questions', ['survey_id'], unique=False)
    op.create_index('idx_occupational_exams_worker_id', 'occupational_exams', ['worker_id'], unique=False)
    op.create_index('idx_occupational_exams_exam_date', 'occupational_exams', ['exam_date'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_enrollments_user_id', 'enrollments', ['user_id'], unique=False)
    op.create_index('idx_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=False)
    op.create_index('idx_enrollments_created_at', 'enrollments', ['created_at'], unique=False)
    op.create_index('idx_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_index('idx_course_modules_course_id', 'course_modules', ['course_id'], unique=False)
    op.create_index('idx_course_materials_module_id', 'course_materials', ['module_id'], unique=False)
    # ### end Alembic commands ###