"""Add permissions table and update role_permissions foreign key

Revision ID: 0dfb477ae18e
Revises: 3b4a346fdd5d
Create Date: 2025-09-04 19:37:47.393957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '0dfb477ae18e'
down_revision = '3b4a346fdd5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_resource_type'), 'permissions', ['resource_type'], unique=False)
    op.execute('DROP INDEX IF EXISTS ix_admin_config_category')
    op.execute('DROP INDEX IF EXISTS ix_admin_config_id')
    op.execute('DROP TABLE IF EXISTS admin_config')
    op.execute('DROP INDEX IF EXISTS ix_programas_id')
    op.execute('DROP TABLE IF EXISTS programas')
    
    # Clear existing role_permissions data before adding foreign key
    op.execute("DELETE FROM role_permissions")
    
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    
    # Insert permissions data
    permissions_table = sa.table('permissions',
        sa.column('id', sa.Integer),
        sa.column('resource_type', sa.String),
        sa.column('action', sa.String),
        sa.column('description', sa.Text),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime)
    )
    
    # Lista de permisos
    permissions_data = [
        {"id": 1, "resource_type": "dashboard", "action": "view", "description": "Acceder al dashboard principal", "is_active": True},
        {"id": 2, "resource_type": "users", "action": "view", "description": "Acceder a la página de usuarios", "is_active": True},
        {"id": 3, "resource_type": "users", "action": "create", "description": "Crear usuarios", "is_active": True},
        {"id": 4, "resource_type": "users", "action": "read", "description": "Ver detalles de usuarios", "is_active": True},
        {"id": 5, "resource_type": "users", "action": "update", "description": "Editar usuarios", "is_active": True},
        {"id": 6, "resource_type": "users", "action": "delete", "description": "Eliminar usuarios", "is_active": True},
        {"id": 7, "resource_type": "courses", "action": "view", "description": "Acceder a la página de cursos", "is_active": True},
        {"id": 8, "resource_type": "courses", "action": "create", "description": "Crear cursos", "is_active": True},
        {"id": 9, "resource_type": "courses", "action": "read", "description": "Ver detalles de cursos", "is_active": True},
        {"id": 10, "resource_type": "courses", "action": "update", "description": "Editar cursos", "is_active": True},
        {"id": 11, "resource_type": "courses", "action": "delete", "description": "Eliminar cursos", "is_active": True},
        {"id": 12, "resource_type": "courses", "action": "enroll", "description": "Inscribirse en cursos", "is_active": True},
        {"id": 13, "resource_type": "evaluations", "action": "view", "description": "Acceder a la página de evaluaciones", "is_active": True},
        {"id": 14, "resource_type": "evaluations", "action": "create", "description": "Crear evaluaciones", "is_active": True},
        {"id": 15, "resource_type": "evaluations", "action": "read", "description": "Ver detalles de evaluaciones", "is_active": True},
        {"id": 16, "resource_type": "evaluations", "action": "update", "description": "Editar evaluaciones", "is_active": True},
        {"id": 17, "resource_type": "evaluations", "action": "delete", "description": "Eliminar evaluaciones", "is_active": True},
        {"id": 18, "resource_type": "evaluations", "action": "submit", "description": "Responder evaluaciones", "is_active": True},
        {"id": 19, "resource_type": "surveys", "action": "view", "description": "Acceder a la página de encuestas", "is_active": True},
        {"id": 20, "resource_type": "surveys", "action": "create", "description": "Crear encuestas", "is_active": True},
        {"id": 21, "resource_type": "surveys", "action": "read", "description": "Ver detalles de encuestas", "is_active": True},
        {"id": 22, "resource_type": "surveys", "action": "update", "description": "Editar encuestas", "is_active": True},
        {"id": 23, "resource_type": "surveys", "action": "delete", "description": "Eliminar encuestas", "is_active": True},
        {"id": 24, "resource_type": "surveys", "action": "submit", "description": "Responder encuestas", "is_active": True},
        {"id": 25, "resource_type": "certificates", "action": "view", "description": "Acceder a la página de certificados", "is_active": True},
        {"id": 26, "resource_type": "certificates", "action": "create", "description": "Generar certificados", "is_active": True},
        {"id": 27, "resource_type": "certificates", "action": "read", "description": "Ver certificados", "is_active": True},
        {"id": 28, "resource_type": "certificates", "action": "update", "description": "Editar certificados", "is_active": True},
        {"id": 29, "resource_type": "certificates", "action": "delete", "description": "Eliminar certificados", "is_active": True},
        {"id": 30, "resource_type": "certificates", "action": "download", "description": "Descargar certificados", "is_active": True},
        {"id": 31, "resource_type": "attendance", "action": "view", "description": "Acceder a la página de asistencia", "is_active": True},
        {"id": 32, "resource_type": "attendance", "action": "create", "description": "Registrar asistencia", "is_active": True},
        {"id": 33, "resource_type": "attendance", "action": "read", "description": "Ver registros de asistencia", "is_active": True},
        {"id": 34, "resource_type": "attendance", "action": "update", "description": "Editar asistencia", "is_active": True},
        {"id": 35, "resource_type": "attendance", "action": "delete", "description": "Eliminar registros de asistencia", "is_active": True},
        {"id": 36, "resource_type": "reports", "action": "view", "description": "Acceder a la página de reportes", "is_active": True},
        {"id": 37, "resource_type": "reports", "action": "create", "description": "Generar reportes", "is_active": True},
        {"id": 38, "resource_type": "reports", "action": "read", "description": "Ver reportes", "is_active": True},
        {"id": 39, "resource_type": "reports", "action": "export", "description": "Exportar reportes", "is_active": True},
        {"id": 40, "resource_type": "notifications", "action": "view", "description": "Acceder a la página de notificaciones", "is_active": True},
        {"id": 41, "resource_type": "notifications", "action": "create", "description": "Crear notificaciones", "is_active": True},
        {"id": 42, "resource_type": "notifications", "action": "read", "description": "Ver notificaciones", "is_active": True},
        {"id": 43, "resource_type": "notifications", "action": "update", "description": "Editar notificaciones", "is_active": True},
        {"id": 44, "resource_type": "notifications", "action": "delete", "description": "Eliminar notificaciones", "is_active": True},
        {"id": 45, "resource_type": "workers", "action": "view", "description": "Acceder a la página de trabajadores", "is_active": True},
        {"id": 46, "resource_type": "workers", "action": "create", "description": "Crear trabajadores", "is_active": True},
        {"id": 47, "resource_type": "workers", "action": "read", "description": "Ver detalles de trabajadores", "is_active": True},
        {"id": 48, "resource_type": "workers", "action": "update", "description": "Editar trabajadores", "is_active": True},
        {"id": 49, "resource_type": "workers", "action": "delete", "description": "Eliminar trabajadores", "is_active": True},
        {"id": 50, "resource_type": "reinductions", "action": "view", "description": "Acceder a la página de reinducciones", "is_active": True},
        {"id": 51, "resource_type": "reinductions", "action": "create", "description": "Crear reinducciones", "is_active": True},
        {"id": 52, "resource_type": "reinductions", "action": "read", "description": "Ver reinducciones", "is_active": True},
        {"id": 53, "resource_type": "reinductions", "action": "update", "description": "Editar reinducciones", "is_active": True},
        {"id": 54, "resource_type": "reinductions", "action": "delete", "description": "Eliminar reinducciones", "is_active": True},
        {"id": 55, "resource_type": "admin_config", "action": "view", "description": "Acceder a configuración administrativa", "is_active": True},
        {"id": 56, "resource_type": "admin_config", "action": "create", "description": "Crear configuraciones", "is_active": True},
        {"id": 57, "resource_type": "admin_config", "action": "read", "description": "Ver configuraciones", "is_active": True},
        {"id": 58, "resource_type": "admin_config", "action": "update", "description": "Editar configuraciones", "is_active": True},
        {"id": 59, "resource_type": "admin_config", "action": "delete", "description": "Eliminar configuraciones", "is_active": True},
        {"id": 60, "resource_type": "health_tracking", "action": "view", "description": "Acceder a seguimiento de salud ocupacional", "is_active": True},
        {"id": 61, "resource_type": "health_tracking", "action": "create", "description": "Crear seguimientos", "is_active": True},
        {"id": 62, "resource_type": "health_tracking", "action": "read", "description": "Ver seguimientos", "is_active": True},
        {"id": 63, "resource_type": "health_tracking", "action": "update", "description": "Editar seguimientos", "is_active": True},
        {"id": 64, "resource_type": "health_tracking", "action": "delete", "description": "Eliminar seguimientos", "is_active": True},
        {"id": 65, "resource_type": "roles", "action": "view", "description": "Acceder a gestión de roles", "is_active": True},
        {"id": 66, "resource_type": "roles", "action": "create", "description": "Crear roles", "is_active": True},
        {"id": 67, "resource_type": "roles", "action": "read", "description": "Ver roles", "is_active": True},
        {"id": 68, "resource_type": "roles", "action": "update", "description": "Editar roles", "is_active": True},
        {"id": 69, "resource_type": "roles", "action": "delete", "description": "Eliminar roles", "is_active": True},
        {"id": 70, "resource_type": "roles", "action": "assign_permissions", "description": "Asignar permisos a roles", "is_active": True},
        {"id": 71, "resource_type": "files", "action": "view", "description": "Acceder a gestión de archivos", "is_active": True},
        {"id": 72, "resource_type": "files", "action": "create", "description": "Subir archivos", "is_active": True},
        {"id": 73, "resource_type": "files", "action": "read", "description": "Ver archivos", "is_active": True},
        {"id": 74, "resource_type": "files", "action": "update", "description": "Editar archivos", "is_active": True},
        {"id": 75, "resource_type": "files", "action": "delete", "description": "Eliminar archivos", "is_active": True},
        {"id": 76, "resource_type": "files", "action": "download", "description": "Descargar archivos", "is_active": True},
        {"id": 77, "resource_type": "modules", "action": "view", "description": "Acceder a la página de módulos", "is_active": True},
        {"id": 78, "resource_type": "modules", "action": "create", "description": "Crear módulos", "is_active": True},
        {"id": 79, "resource_type": "modules", "action": "read", "description": "Ver detalles de módulos", "is_active": True},
        {"id": 80, "resource_type": "modules", "action": "update", "description": "Editar módulos", "is_active": True},
        {"id": 81, "resource_type": "modules", "action": "delete", "description": "Eliminar módulos", "is_active": True},
        {"id": 82, "resource_type": "materials", "action": "view", "description": "Acceder a la página de materiales", "is_active": True},
        {"id": 83, "resource_type": "materials", "action": "create", "description": "Crear materiales", "is_active": True},
        {"id": 84, "resource_type": "materials", "action": "read", "description": "Ver detalles de materiales", "is_active": True},
        {"id": 85, "resource_type": "materials", "action": "update", "description": "Editar materiales", "is_active": True},
        {"id": 86, "resource_type": "materials", "action": "delete", "description": "Eliminar materiales", "is_active": True}
    ]
    
    # Insert permissions
    for perm in permissions_data:
        op.execute(
            permissions_table.insert().values(
                id=perm["id"],
                resource_type=perm["resource_type"],
                action=perm["action"],
                description=perm["description"],
                is_active=perm["is_active"],
                created_at=datetime.utcnow(),
                updated_at=datetime.utcnow()
            )
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('programas_pkey'))
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    op.create_table('admin_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('emo_periodicity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_config_pkey'))
    )
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_index(op.f('ix_admin_config_category'), 'admin_config', ['category'], unique=False)
    op.drop_index(op.f('ix_permissions_resource_type'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###