"""add_sst_management_data_to_homework_assessment

Revision ID: 15de284399be
Revises: 4d1ca1b7939e
Create Date: 2026-02-09 16:26:32.193052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15de284399be'
down_revision = '4d1ca1b7939e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_assessments', sa.Column('sst_management_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework_assessments', 'sst_management_data')
    # ### end Alembic commands ###