"""add_otrosi_to_documentcategory_enum

Revision ID: 161bd49b6aab
Revises: 1e0aea582921
Create Date: 2025-09-25 16:17:35.250053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161bd49b6aab'
down_revision = '1e0aea582921'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar el nuevo valor 'otrosi' al enum documentcategory
    op.execute("ALTER TYPE documentcategory ADD VALUE 'otrosi'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: PostgreSQL no permite eliminar valores de un enum directamente
    # Se requeriría recrear el enum completo, lo cual es complejo
    # Por simplicidad, dejamos el downgrade vacío
    pass
    # ### end Alembic commands ###