"""update_committee_type_enum_to_lowercase

Revision ID: 1b4fe8606608
Revises: 4bf9958d5e4e
Create Date: 2025-09-28 20:47:54.904530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4fe8606608'
down_revision = '4bf9958d5e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if we need to add the lowercase values
    # First, check what values currently exist
    connection = op.get_bind()
    
    # Get current enum values
    result = connection.execute(sa.text("""
        SELECT e.enumlabel 
        FROM pg_type t 
        JOIN pg_enum e ON t.oid = e.enumtypid 
        WHERE t.typname = 'committeetypeenum'
        ORDER BY e.enumsortorder
    """))
    current_values = [row[0] for row in result.fetchall()]
    
    # Add lowercase values if they don't exist
    if 'copasst' not in current_values:
        op.execute("ALTER TYPE committeetypeenum ADD VALUE 'copasst'")
    if 'convivencia' not in current_values:
        op.execute("ALTER TYPE committeetypeenum ADD VALUE 'convivencia'")
    
    # Commit the enum changes before using them
    connection.commit()
    
    # Update existing data to use lowercase values
    if 'COPASST' in current_values:
        op.execute("UPDATE committees SET committee_type = 'copasst' WHERE committee_type = 'COPASST'")
    if 'CONVIVENCIA' in current_values:
        op.execute("UPDATE committees SET committee_type = 'convivencia' WHERE committee_type = 'CONVIVENCIA'")
    
    # Note: PostgreSQL doesn't allow removing enum values directly
    # The old uppercase values will remain in the enum but won't be used
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert the data back to uppercase values
    op.execute("UPDATE committees SET committee_type = 'COPASST' WHERE committee_type = 'copasst'")
    op.execute("UPDATE committees SET committee_type = 'CONVIVENCIA' WHERE committee_type = 'convivencia'")
    
    # ### end Alembic commands ###