"""Agregar OTROSI al enum NovedadType

Revision ID: 1e0aea582921
Revises: 0ea8f3978fbc
Create Date: 2025-09-25 21:56:54.506350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0aea582921'
down_revision = '0ea8f3978fbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar el nuevo valor 'otrosi' al enum NovedadType
    op.execute("ALTER TYPE novedadtype ADD VALUE 'otrosi'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: PostgreSQL no permite eliminar valores de un enum directamente
    # Se requeriría recrear el enum completo, lo cual es complejo
    # Por simplicidad, dejamos el downgrade vacío
    pass
    # ### end Alembic commands ###