"""add_worker_novedades_table_v2

Revision ID: 20fba412cfd0
Revises: 2a22a6ede896
Create Date: 2025-09-11 00:07:32.234173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fba412cfd0'
down_revision = 'eb42a14a850a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PERMISO_DIA_FAMILIA', 'LICENCIA_PATERNIDAD', 'INCAPACIDAD_MEDICA', 'PERMISO_DIA_NO_REMUNERADO', 'AUMENTO_SALARIO', 'LICENCIA_MATERNIDAD', 'HORAS_EXTRAS', 'RECARGOS', name='novedadtype'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', 'PROCESADA', name='novedadstatus'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('dias_calculados', sa.Integer(), nullable=True),
    sa.Column('salario_anterior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_nuevo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_aumento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cantidad_horas', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('valor_hora', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documento_soporte', sa.String(length=500), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_novedades_id'), 'worker_novedades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_novedades_id'), table_name='worker_novedades')
    op.drop_table('worker_novedades')
    # ### end Alembic commands ###