"""Add requires_follow_up field to occupational_exam table

Revision ID: 2b0c3dbbc4e8
Revises: 0d3b7dcdb7ea
Create Date: 2025-10-30 18:07:51.803573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b0c3dbbc4e8'
down_revision = '0d3b7dcdb7ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_programas_id', table_name='programas')
    op.drop_table('programas')
    # Add requires_follow_up column with default value False for existing records
    op.add_column('occupational_exams', sa.Column('requires_follow_up', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('seguimientos', sa.Column('occupational_exam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seguimientos', 'occupational_exams', ['occupational_exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seguimientos', type_='foreignkey')
    op.drop_column('seguimientos', 'occupational_exam_id')
    op.drop_column('occupational_exams', 'requires_follow_up')
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='programas_pkey')
    )
    op.create_index('ix_programas_id', 'programas', ['id'], unique=False)
    # ### end Alembic commands ###