"""make_doctor_document_number_optional

Revision ID: 3b4a346fdd5d
Revises: 0759ab86c607
Create Date: 2025-09-03 20:58:15.069578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4a346fdd5d'
down_revision = '0759ab86c607'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique constraint on document_number
    op.drop_index('ix_doctors_document_number', table_name='doctors')
    
    # Alter the column to be nullable
    op.alter_column('doctors', 'document_number',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    
    # Recreate the index without unique constraint
    op.create_index(op.f('ix_doctors_document_number'), 'doctors', ['document_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the non-unique index
    op.drop_index(op.f('ix_doctors_document_number'), table_name='doctors')
    
    # Alter the column to be non-nullable
    op.alter_column('doctors', 'document_number',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    
    # Recreate the unique index
    op.create_index('ix_doctors_document_number', 'doctors', ['document_number'], unique=True)
    # ### end Alembic commands ###