"""update_document_type_enum_add_missing_values

Revision ID: 3eafeb73255b
Revises: 03e987fcd84c
Create Date: 2025-09-26 20:22:55.664408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eafeb73255b'
down_revision = '03e987fcd84c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new values to the DocumentTypeEnum
    op.execute("ALTER TYPE documenttypeenum ADD VALUE IF NOT EXISTS 'activity_report'")
    op.execute("ALTER TYPE documenttypeenum ADD VALUE IF NOT EXISTS 'agreement'")
    op.execute("ALTER TYPE documenttypeenum ADD VALUE IF NOT EXISTS 'presentation'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum type and updating all references
    # For now, we'll leave the values in place as they don't cause harm
    pass
    # ### end Alembic commands ###