"""Create programas table

Revision ID: 4491bdc63049
Revises: cdbab7e8f7e8
Create Date: 2025-09-21 23:08:51.429523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4491bdc63049'
down_revision = 'cdbab7e8f7e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    # ### end Alembic commands ###