"""add_voting_record_to_document_type_enum

Revision ID: 4bf9958d5e4e
Revises: 3eafeb73255b
Create Date: 2025-09-26 22:02:57.550187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf9958d5e4e'
down_revision = '3eafeb73255b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'voting_record' to the DocumentTypeEnum
    op.execute("ALTER TYPE documenttypeenum ADD VALUE 'voting_record'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing enum values directly
    # This would require recreating the enum and updating all references
    pass
    # ### end Alembic commands ###