"""fix_exam_type_nullable

Revision ID: 4c7c553077a2
Revises: 0a173e668dc1
Create Date: 2026-01-23 16:25:54.591921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c7c553077a2'
down_revision = '0a173e668dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('occupational_exams', 'tipo_examen_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.drop_column('occupational_exams', 'exam_type')
    op.alter_column('occupational_exams', 'exam_type', existing_type=postgresql.ENUM('INGRESO', 'PERIODICO', 'REINTEGRO', 'RETIRO', name='examtype'), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('occupational_exams', sa.Column('exam_type', postgresql.ENUM('INGRESO', 'PERIODICO', 'REINTEGRO', 'RETIRO', name='examtype'), autoincrement=False, nullable=False))
    op.alter_column('occupational_exams', 'exam_type', existing_type=postgresql.ENUM('INGRESO', 'PERIODICO', 'REINTEGRO', 'RETIRO', name='examtype'), nullable=False)
    # op.alter_column('occupational_exams', 'tipo_examen_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # ### end Alembic commands ###