"""create vacation_balances table

Revision ID: 6a0d8f5800de
Revises: 8daac6c61af5
Create Date: 2025-09-22 18:59:39.984193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0d8f5800de'
down_revision = '8daac6c61af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###