"""Add matrix fields to occupational_exam

Revision ID: 72bb6d50db7a
Revises: d3f4e5a6b7c8
Create Date: 2026-02-23 22:01:31.358739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72bb6d50db7a'
down_revision = 'd3f4e5a6b7c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types if they don't exist
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activitytype') THEN CREATE TYPE activitytype AS ENUM ('drag_drop', 'matching', 'ordering', 'hotspot', 'fill_blanks'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lessonnavigationtype') THEN CREATE TYPE lessonnavigationtype AS ENUM ('sequential', 'free'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'lessonstatus') THEN CREATE TYPE lessonstatus AS ENUM ('draft', 'published', 'archived'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'slidecontenttype') THEN CREATE TYPE slidecontenttype AS ENUM ('text', 'image', 'video', 'text_image', 'quiz', 'interactive'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ciclophva') THEN CREATE TYPE ciclophva AS ENUM ('I_PLANEAR', 'II_HACER', 'III_VERIFICAR', 'IV_ACTUAR'); END IF; END $$;")

    # Drop defaults that might interfere with type changes
    op.execute("ALTER TABLE interactive_lessons ALTER COLUMN navigation_type DROP DEFAULT")
    op.execute("ALTER TABLE interactive_lessons ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE plan_trabajo_anual ALTER COLUMN estado DROP DEFAULT")

    op.alter_column('criterios_exclusion', 'activo',

               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('cronograma_pyp', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('cronograma_pyp', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint('cronograma_pyp_plan_trabajo_anual_id_fkey', 'cronograma_pyp', type_='foreignkey')
    op.create_foreign_key(None, 'cronograma_pyp', 'plan_trabajo_anual', ['plan_trabajo_anual_id'], ['id'])
    op.alter_column('cronograma_pyp_actividad', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('cronograma_pyp_actividad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint('cronograma_pyp_actividad_cronograma_id_fkey', 'cronograma_pyp_actividad', type_='foreignkey')
    op.create_foreign_key(None, 'cronograma_pyp_actividad', 'cronograma_pyp', ['cronograma_id'], ['id'])
    op.alter_column('cronograma_pyp_seguimiento', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('cronograma_pyp_seguimiento', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint('uq_cronograma_pyp_actividad_mes', 'cronograma_pyp_seguimiento', type_='unique')
    op.drop_constraint('cronograma_pyp_seguimiento_actividad_id_fkey', 'cronograma_pyp_seguimiento', type_='foreignkey')
    op.create_foreign_key(None, 'cronograma_pyp_seguimiento', 'cronograma_pyp_actividad', ['actividad_id'], ['id'])
    op.alter_column('empresas', 'tiene_trabajadores_independientes',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_teletrabajo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_alturas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_espacios_confinados',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_caliente',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_sustancias_quimicas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_radiaciones',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_nocturno',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_menores_edad',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_mujeres_embarazadas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_conductores',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_manipulacion_alimentos',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_maquinaria_pesada',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_riesgo_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_riesgo_biologico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_excavaciones',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_administrativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('inline_quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('inline_quiz_answers', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_inline_quiz_answers_quiz_id', table_name='inline_quiz_answers')
    op.drop_constraint('inline_quiz_answers_quiz_id_fkey', 'inline_quiz_answers', type_='foreignkey')
    op.create_foreign_key(None, 'inline_quiz_answers', 'inline_quizzes', ['quiz_id'], ['id'])
    op.alter_column('inline_quizzes', 'question_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'OPEN_TEXT', name='questiontype'),
               existing_nullable=False,
               postgresql_using='UPPER(question_type)::questiontype')
    op.alter_column('inline_quizzes', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('inline_quizzes', 'required_to_continue',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('inline_quizzes', 'show_feedback_immediately',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('inline_quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('inline_quizzes_slide_id_fkey', 'inline_quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'inline_quizzes', 'lesson_slides', ['slide_id'], ['id'])
    op.alter_column('interactive_activities', 'activity_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('drag_drop', 'matching', 'ordering', 'hotspot', 'fill_blanks', name='activitytype'),
               existing_nullable=False,
               postgresql_using='LOWER(activity_type)::activitytype')
    op.alter_column('interactive_activities', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_activities', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_activities', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_activities', 'show_feedback',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_interactive_activities_lesson_id', table_name='interactive_activities')
    op.drop_constraint('interactive_activities_slide_id_fkey', 'interactive_activities', type_='foreignkey')
    op.drop_constraint('interactive_activities_lesson_id_fkey', 'interactive_activities', type_='foreignkey')
    op.create_foreign_key(None, 'interactive_activities', 'interactive_lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'interactive_activities', 'lesson_slides', ['slide_id'], ['id'])
    op.alter_column('interactive_lessons', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_lessons', 'navigation_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('sequential', 'free', name='lessonnavigationtype'),
               nullable=True,
               postgresql_using='LOWER(navigation_type)::lessonnavigationtype')
    op.alter_column('interactive_lessons', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('draft', 'published', 'archived', name='lessonstatus'),
               nullable=True,
               postgresql_using='LOWER(status)::lessonstatus')
    op.alter_column('interactive_lessons', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_lessons', 'passing_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('interactive_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_interactive_lessons_module_id', table_name='interactive_lessons')
    op.drop_index('ix_interactive_lessons_status', table_name='interactive_lessons')
    op.drop_constraint('interactive_lessons_module_id_fkey', 'interactive_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'interactive_lessons', 'course_modules', ['module_id'], ['id'])
    op.alter_column('lesson_slides', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('lesson_slides', 'slide_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('text', 'image', 'video', 'text_image', 'quiz', 'interactive', name='slidecontenttype'),
               existing_nullable=False,
               postgresql_using='LOWER(slide_type)::slidecontenttype')
    op.alter_column('lesson_slides', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('lesson_slides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_lesson_slides_lesson_id', table_name='lesson_slides')
    op.drop_constraint('lesson_slides_lesson_id_fkey', 'lesson_slides', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_slides', 'interactive_lessons', ['lesson_id'], ['id'])
    op.alter_column('master_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('master_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_cumplimientos', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_cumplimientos', 'aplica_empresa',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_cumplimientos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_matriz_legal_cumplimientos_empresa', table_name='matriz_legal_cumplimientos')
    op.drop_index('ix_matriz_legal_cumplimientos_norma', table_name='matriz_legal_cumplimientos')
    op.create_index(op.f('ix_matriz_legal_cumplimientos_empresa_id'), 'matriz_legal_cumplimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_matriz_legal_cumplimientos_norma_id'), 'matriz_legal_cumplimientos', ['norma_id'], unique=False)
    op.drop_constraint('matriz_legal_cumplimientos_empresa_id_fkey', 'matriz_legal_cumplimientos', type_='foreignkey')
    op.drop_constraint('matriz_legal_cumplimientos_norma_id_fkey', 'matriz_legal_cumplimientos', type_='foreignkey')
    op.create_foreign_key(None, 'matriz_legal_cumplimientos', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'matriz_legal_cumplimientos', 'matriz_legal_normas', ['norma_id'], ['id'])
    op.alter_column('matriz_legal_cumplimientos_historial', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_matriz_legal_cumplimientos_historial_cumplimiento', table_name='matriz_legal_cumplimientos_historial')
    op.create_index(op.f('ix_matriz_legal_cumplimientos_historial_cumplimiento_id'), 'matriz_legal_cumplimientos_historial', ['cumplimiento_id'], unique=False)
    op.drop_constraint('matriz_legal_cumplimientos_historial_cumplimiento_id_fkey', 'matriz_legal_cumplimientos_historial', type_='foreignkey')
    op.create_foreign_key(None, 'matriz_legal_cumplimientos_historial', 'matriz_legal_cumplimientos', ['cumplimiento_id'], ['id'])
    op.alter_column('matriz_legal_importaciones', 'fecha_importacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_importaciones', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_importaciones', 'total_filas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_nuevas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_actualizadas',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_sin_cambios',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'errores',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'ambito_aplicacion',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajadores_independientes',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_teletrabajo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_alturas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_espacios_confinados',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_caliente',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_sustancias_quimicas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_radiaciones',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_nocturno',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_menores_edad',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_mujeres_embarazadas',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_conductores',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_manipulacion_alimentos',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_maquinaria_pesada',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_riesgo_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_riesgo_biologico',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_excavaciones',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_administrativo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_general',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_matriz_legal_normas_ambito', table_name='matriz_legal_normas')
    op.drop_index('ix_matriz_legal_normas_clasificacion', table_name='matriz_legal_normas')
    op.drop_index('ix_matriz_legal_normas_tema', table_name='matriz_legal_normas')
    op.drop_index('ix_matriz_legal_normas_tipo_numero', table_name='matriz_legal_normas')
    op.create_index(op.f('ix_matriz_legal_normas_ambito_aplicacion'), 'matriz_legal_normas', ['ambito_aplicacion'], unique=False)
    op.create_index(op.f('ix_matriz_legal_normas_clasificacion_norma'), 'matriz_legal_normas', ['clasificacion_norma'], unique=False)
    op.create_index(op.f('ix_matriz_legal_normas_numero_norma'), 'matriz_legal_normas', ['numero_norma'], unique=False)
    op.create_index(op.f('ix_matriz_legal_normas_tema_general'), 'matriz_legal_normas', ['tema_general'], unique=False)
    op.create_index(op.f('ix_matriz_legal_normas_tipo_norma'), 'matriz_legal_normas', ['tipo_norma'], unique=False)
    op.alter_column('matriz_legal_normas_historial', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('matriz_legal_normas_historial_norma_id_fkey', 'matriz_legal_normas_historial', type_='foreignkey')
    op.create_foreign_key(None, 'matriz_legal_normas_historial', 'matriz_legal_normas', ['norma_id'], ['id'])
    op.add_column('occupational_exams', sa.Column('matrix_i_check', sa.Boolean(), nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_p_check', sa.Boolean(), nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_e_check', sa.Boolean(), nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_carta_check', sa.Boolean(), nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_plan_accion', sa.Text(), nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_seguimiento', sa.Text(), nullable=True))
    op.alter_column('occupational_exams', 'exam_type',
               existing_type=postgresql.ENUM('INGRESO', 'PERIODICO', 'REINTEGRO', 'RETIRO', name='examtype'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('plan_trabajo_actividad', 'ciclo',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('I_PLANEAR', 'II_HACER', 'III_VERIFICAR', 'IV_ACTUAR', name='ciclophva'),
               existing_nullable=False,
               postgresql_using='ciclo::ciclophva')
    op.alter_column('plan_trabajo_actividad', 'categoria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('RECURSOS', 'GESTION_INTEGRAL', 'GESTION_SALUD', 'GESTION_PELIGROS', 'GESTION_AMENAZAS', 'VERIFICACION', 'MEJORAMIENTO', name='categoriaactividad'),
               existing_nullable=False,
               postgresql_using='categoria::categoriaactividad')
    op.alter_column('plan_trabajo_actividad', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('plan_trabajo_actividad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint('plan_trabajo_actividad_plan_id_fkey', 'plan_trabajo_actividad', type_='foreignkey')
    op.create_foreign_key(None, 'plan_trabajo_actividad', 'plan_trabajo_anual', ['plan_id'], ['id'])
    op.alter_column('plan_trabajo_anual', 'estado',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('borrador', 'aprobado', 'en_ejecucion', 'finalizado', name='estadoplan'),
               existing_nullable=True,
               postgresql_using='LOWER(estado)::estadoplan')
    op.alter_column('plan_trabajo_anual', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('plan_trabajo_anual', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('plan_trabajo_seguimiento', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('plan_trabajo_seguimiento', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint('plan_trabajo_seguimiento_actividad_id_fkey', 'plan_trabajo_seguimiento', type_='foreignkey')
    op.create_foreign_key(None, 'plan_trabajo_seguimiento', 'plan_trabajo_actividad', ['actividad_id'], ['id'])
    op.alter_column('presupuesto_categoria', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_categoria', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_presupuesto_categoria_id'), 'presupuesto_categoria', ['id'], unique=False)
    op.alter_column('presupuesto_item', 'es_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_item', 'orden',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('presupuesto_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_presupuesto_item_id'), 'presupuesto_item', ['id'], unique=False)
    op.alter_column('presupuesto_mensual', 'proyectado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_mensual', 'ejecutado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_mensual', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('presupuesto_mensual', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_presupuesto_mensual_id'), 'presupuesto_mensual', ['id'], unique=False)
    op.alter_column('presupuesto_sst', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_sst', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('presupuesto_sst', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('presupuesto_sst', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_presupuesto_sst_id'), 'presupuesto_sst', ['id'], unique=False)
    op.alter_column('sectores_economicos', 'es_todos_los_sectores',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sectores_economicos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sectores_economicos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_activity_attempts', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('user_activity_attempts', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('user_activity_attempts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('user_activity_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_activity_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_activity_attempts_activity_id', table_name='user_activity_attempts')
    op.drop_index('ix_user_activity_attempts_user_id', table_name='user_activity_attempts')
    op.drop_constraint('user_activity_attempts_enrollment_id_fkey', 'user_activity_attempts', type_='foreignkey')
    op.drop_constraint('user_activity_attempts_user_id_fkey', 'user_activity_attempts', type_='foreignkey')
    op.drop_constraint('user_activity_attempts_activity_id_fkey', 'user_activity_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'user_activity_attempts', 'interactive_activities', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'user_activity_attempts', 'enrollments', ['enrollment_id'], ['id'])
    op.create_foreign_key(None, 'user_activity_attempts', 'users', ['user_id'], ['id'])
    op.alter_column('user_lesson_progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'current_slide_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'progress_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'quiz_total_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'quiz_earned_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('user_lesson_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_lesson_progress_lesson_id', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_unique', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_user_id', table_name='user_lesson_progress')
    op.drop_constraint('user_lesson_progress_user_id_fkey', 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint('user_lesson_progress_enrollment_id_fkey', 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint('user_lesson_progress_lesson_id_fkey', 'user_lesson_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_lesson_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson_progress', 'interactive_lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'user_lesson_progress', 'enrollments', ['enrollment_id'], ['id'])
    op.alter_column('user_slide_progress', 'viewed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('user_slide_progress', 'quiz_answered',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('user_slide_progress', 'quiz_correct',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('user_slide_progress', 'quiz_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('user_slide_progress', 'points_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               nullable=True)
    op.alter_column('user_slide_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_user_slide_progress_unique', table_name='user_slide_progress')
    op.drop_constraint('user_slide_progress_slide_id_fkey', 'user_slide_progress', type_='foreignkey')
    op.drop_constraint('user_slide_progress_lesson_progress_id_fkey', 'user_slide_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_slide_progress', 'lesson_slides', ['slide_id'], ['id'])
    op.create_foreign_key(None, 'user_slide_progress', 'user_lesson_progress', ['lesson_progress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_slide_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_slide_progress', type_='foreignkey')
    op.create_foreign_key('user_slide_progress_lesson_progress_id_fkey', 'user_slide_progress', 'user_lesson_progress', ['lesson_progress_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_slide_progress_slide_id_fkey', 'user_slide_progress', 'lesson_slides', ['slide_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_slide_progress_unique', 'user_slide_progress', ['lesson_progress_id', 'slide_id'], unique=True)
    op.alter_column('user_slide_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_slide_progress', 'points_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('user_slide_progress', 'quiz_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user_slide_progress', 'quiz_correct',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('user_slide_progress', 'quiz_answered',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('user_slide_progress', 'viewed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_constraint(None, 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_lesson_progress', type_='foreignkey')
    op.create_foreign_key('user_lesson_progress_lesson_id_fkey', 'user_lesson_progress', 'interactive_lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_lesson_progress_enrollment_id_fkey', 'user_lesson_progress', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_lesson_progress_user_id_fkey', 'user_lesson_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_lesson_progress_user_id', 'user_lesson_progress', ['user_id'], unique=False)
    op.create_index('ix_user_lesson_progress_unique', 'user_lesson_progress', ['user_id', 'lesson_id', 'enrollment_id'], unique=True)
    op.create_index('ix_user_lesson_progress_lesson_id', 'user_lesson_progress', ['lesson_id'], unique=False)
    op.alter_column('user_lesson_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_lesson_progress', 'time_spent_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user_lesson_progress', 'quiz_earned_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('user_lesson_progress', 'quiz_total_points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('user_lesson_progress', 'progress_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('user_lesson_progress', 'current_slide_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('user_lesson_progress', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'not_started'::character varying"),
               nullable=False)
    op.drop_constraint(None, 'user_activity_attempts', type_='foreignkey')
    op.drop_constraint(None, 'user_activity_attempts', type_='foreignkey')
    op.drop_constraint(None, 'user_activity_attempts', type_='foreignkey')
    op.create_foreign_key('user_activity_attempts_activity_id_fkey', 'user_activity_attempts', 'interactive_activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_activity_attempts_user_id_fkey', 'user_activity_attempts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_activity_attempts_enrollment_id_fkey', 'user_activity_attempts', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_activity_attempts_user_id', 'user_activity_attempts', ['user_id'], unique=False)
    op.create_index('ix_user_activity_attempts_activity_id', 'user_activity_attempts', ['activity_id'], unique=False)
    op.alter_column('user_activity_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_activity_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_activity_attempts', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               nullable=False)
    op.alter_column('user_activity_attempts', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('user_activity_attempts', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=False)
    op.alter_column('sectores_economicos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sectores_economicos', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('sectores_economicos', 'es_todos_los_sectores',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_presupuesto_sst_id'), table_name='presupuesto_sst')
    op.alter_column('presupuesto_sst', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_sst', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_sst', 'version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1'::character varying"),
               existing_nullable=True)
    op.alter_column('presupuesto_sst', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'AN-SST-03'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_presupuesto_mensual_id'), table_name='presupuesto_mensual')
    op.alter_column('presupuesto_mensual', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_mensual', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_mensual', 'ejecutado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('presupuesto_mensual', 'proyectado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.drop_index(op.f('ix_presupuesto_item_id'), table_name='presupuesto_item')
    op.alter_column('presupuesto_item', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_item', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('presupuesto_item', 'es_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.drop_index(op.f('ix_presupuesto_categoria_id'), table_name='presupuesto_categoria')
    op.alter_column('presupuesto_categoria', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('presupuesto_categoria', 'orden',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_constraint(None, 'plan_trabajo_seguimiento', type_='foreignkey')
    op.create_foreign_key('plan_trabajo_seguimiento_actividad_id_fkey', 'plan_trabajo_seguimiento', 'plan_trabajo_actividad', ['actividad_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plan_trabajo_seguimiento', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_seguimiento', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_anual', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_anual', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_anual', 'estado',
               existing_type=sa.Enum('BORRADOR', 'APROBADO', 'EN_EJECUCION', 'FINALIZADO', name='estadoplan'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_constraint(None, 'plan_trabajo_actividad', type_='foreignkey')
    op.create_foreign_key('plan_trabajo_actividad_plan_id_fkey', 'plan_trabajo_actividad', 'plan_trabajo_anual', ['plan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plan_trabajo_actividad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_actividad', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('plan_trabajo_actividad', 'categoria',
               existing_type=sa.Enum('RECURSOS', 'GESTION_INTEGRAL', 'GESTION_SALUD', 'GESTION_PELIGROS', 'GESTION_AMENAZAS', 'VERIFICACION', 'MEJORAMIENTO', name='categoriaactividad'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('plan_trabajo_actividad', 'ciclo',
               existing_type=sa.Enum('I_PLANEAR', 'II_HACER', 'III_VERIFICAR', 'IV_ACTUAR', name='ciclophva'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('occupational_exams', 'exam_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('INGRESO', 'PERIODICO', 'REINTEGRO', 'RETIRO', name='examtype'),
               existing_nullable=True)
    op.drop_column('occupational_exams', 'matrix_seguimiento')
    op.drop_column('occupational_exams', 'matrix_plan_accion')
    op.drop_column('occupational_exams', 'matrix_carta_check')
    op.drop_column('occupational_exams', 'matrix_e_check')
    op.drop_column('occupational_exams', 'matrix_p_check')
    op.drop_column('occupational_exams', 'matrix_i_check')
    op.drop_constraint(None, 'matriz_legal_normas_historial', type_='foreignkey')
    op.create_foreign_key('matriz_legal_normas_historial_norma_id_fkey', 'matriz_legal_normas_historial', 'matriz_legal_normas', ['norma_id'], ['id'], ondelete='CASCADE')
    op.alter_column('matriz_legal_normas_historial', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_matriz_legal_normas_tipo_norma'), table_name='matriz_legal_normas')
    op.drop_index(op.f('ix_matriz_legal_normas_tema_general'), table_name='matriz_legal_normas')
    op.drop_index(op.f('ix_matriz_legal_normas_numero_norma'), table_name='matriz_legal_normas')
    op.drop_index(op.f('ix_matriz_legal_normas_clasificacion_norma'), table_name='matriz_legal_normas')
    op.drop_index(op.f('ix_matriz_legal_normas_ambito_aplicacion'), table_name='matriz_legal_normas')
    op.create_index('ix_matriz_legal_normas_tipo_numero', 'matriz_legal_normas', ['tipo_norma', 'numero_norma'], unique=False)
    op.create_index('ix_matriz_legal_normas_tema', 'matriz_legal_normas', ['tema_general'], unique=False)
    op.create_index('ix_matriz_legal_normas_clasificacion', 'matriz_legal_normas', ['clasificacion_norma'], unique=False)
    op.create_index('ix_matriz_legal_normas_ambito', 'matriz_legal_normas', ['ambito_aplicacion'], unique=False)
    op.alter_column('matriz_legal_normas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_general',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_administrativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_excavaciones',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_riesgo_biologico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_riesgo_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_maquinaria_pesada',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_manipulacion_alimentos',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_conductores',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_mujeres_embarazadas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_menores_edad',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_nocturno',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_radiaciones',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_sustancias_quimicas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_caliente',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_espacios_confinados',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajo_alturas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_teletrabajo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'aplica_trabajadores_independientes',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'vigente'::character varying"),
               existing_nullable=False)
    op.alter_column('matriz_legal_normas', 'ambito_aplicacion',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'nacional'::character varying"),
               existing_nullable=False)
    op.alter_column('matriz_legal_importaciones', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('matriz_legal_importaciones', 'errores',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_sin_cambios',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_actualizadas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'normas_nuevas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'total_filas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('matriz_legal_importaciones', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'en_proceso'::character varying"),
               existing_nullable=False)
    op.alter_column('matriz_legal_importaciones', 'fecha_importacion',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'matriz_legal_cumplimientos_historial', type_='foreignkey')
    op.create_foreign_key('matriz_legal_cumplimientos_historial_cumplimiento_id_fkey', 'matriz_legal_cumplimientos_historial', 'matriz_legal_cumplimientos', ['cumplimiento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_matriz_legal_cumplimientos_historial_cumplimiento_id'), table_name='matriz_legal_cumplimientos_historial')
    op.create_index('ix_matriz_legal_cumplimientos_historial_cumplimiento', 'matriz_legal_cumplimientos_historial', ['cumplimiento_id'], unique=False)
    op.alter_column('matriz_legal_cumplimientos_historial', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'matriz_legal_cumplimientos', type_='foreignkey')
    op.drop_constraint(None, 'matriz_legal_cumplimientos', type_='foreignkey')
    op.create_foreign_key('matriz_legal_cumplimientos_norma_id_fkey', 'matriz_legal_cumplimientos', 'matriz_legal_normas', ['norma_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('matriz_legal_cumplimientos_empresa_id_fkey', 'matriz_legal_cumplimientos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_matriz_legal_cumplimientos_norma_id'), table_name='matriz_legal_cumplimientos')
    op.drop_index(op.f('ix_matriz_legal_cumplimientos_empresa_id'), table_name='matriz_legal_cumplimientos')
    op.create_index('ix_matriz_legal_cumplimientos_norma', 'matriz_legal_cumplimientos', ['norma_id'], unique=False)
    op.create_index('ix_matriz_legal_cumplimientos_empresa', 'matriz_legal_cumplimientos', ['empresa_id'], unique=False)
    op.alter_column('matriz_legal_cumplimientos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('matriz_legal_cumplimientos', 'aplica_empresa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('matriz_legal_cumplimientos', 'estado',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pendiente'::character varying"),
               existing_nullable=False)
    op.alter_column('master_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('master_documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'lesson_slides', type_='foreignkey')
    op.create_foreign_key('lesson_slides_lesson_id_fkey', 'lesson_slides', 'interactive_lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_lesson_slides_lesson_id', 'lesson_slides', ['lesson_id'], unique=False)
    op.alter_column('lesson_slides', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('lesson_slides', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('lesson_slides', 'slide_type',
               existing_type=sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'TEXT_IMAGE', 'QUIZ', 'INTERACTIVE', name='slidecontenttype'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('lesson_slides', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_constraint(None, 'interactive_lessons', type_='foreignkey')
    op.create_foreign_key('interactive_lessons_module_id_fkey', 'interactive_lessons', 'course_modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_interactive_lessons_status', 'interactive_lessons', ['status'], unique=False)
    op.create_index('ix_interactive_lessons_module_id', 'interactive_lessons', ['module_id'], unique=False)
    op.alter_column('interactive_lessons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('interactive_lessons', 'passing_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'70'::double precision"),
               nullable=False)
    op.alter_column('interactive_lessons', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('interactive_lessons', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='lessonstatus'),
               server_default=sa.text("'draft'::character varying"),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('interactive_lessons', 'navigation_type',
               existing_type=sa.Enum('SEQUENTIAL', 'FREE', name='lessonnavigationtype'),
               server_default=sa.text("'sequential'::character varying"),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('interactive_lessons', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.drop_constraint(None, 'interactive_activities', type_='foreignkey')
    op.drop_constraint(None, 'interactive_activities', type_='foreignkey')
    op.create_foreign_key('interactive_activities_lesson_id_fkey', 'interactive_activities', 'interactive_lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('interactive_activities_slide_id_fkey', 'interactive_activities', 'lesson_slides', ['slide_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_interactive_activities_lesson_id', 'interactive_activities', ['lesson_id'], unique=False)
    op.alter_column('interactive_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('interactive_activities', 'show_feedback',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('interactive_activities', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               nullable=False)
    op.alter_column('interactive_activities', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               nullable=False)
    op.alter_column('interactive_activities', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('interactive_activities', 'activity_type',
               existing_type=sa.Enum('DRAG_DROP', 'MATCHING', 'ORDERING', 'HOTSPOT', 'FILL_BLANKS', name='activitytype'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'inline_quizzes', type_='foreignkey')
    op.create_foreign_key('inline_quizzes_slide_id_fkey', 'inline_quizzes', 'lesson_slides', ['slide_id'], ['id'], ondelete='CASCADE')
    op.alter_column('inline_quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('inline_quizzes', 'show_feedback_immediately',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('inline_quizzes', 'required_to_continue',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('inline_quizzes', 'points',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               nullable=False)
    op.alter_column('inline_quizzes', 'question_type',
               existing_type=sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'OPEN_TEXT', name='questiontype'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'inline_quiz_answers', type_='foreignkey')
    op.create_foreign_key('inline_quiz_answers_quiz_id_fkey', 'inline_quiz_answers', 'inline_quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_inline_quiz_answers_quiz_id', 'inline_quiz_answers', ['quiz_id'], unique=False)
    op.alter_column('inline_quiz_answers', 'order_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('inline_quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('empresas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('empresas', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_administrativo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_excavaciones',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_riesgo_biologico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_riesgo_electrico',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_maquinaria_pesada',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_manipulacion_alimentos',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_conductores',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_mujeres_embarazadas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_menores_edad',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_nocturno',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_radiaciones',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_sustancias_quimicas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_caliente',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_espacios_confinados',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajo_alturas',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_teletrabajo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('empresas', 'tiene_trabajadores_independientes',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'cronograma_pyp_seguimiento', type_='foreignkey')
    op.create_foreign_key('cronograma_pyp_seguimiento_actividad_id_fkey', 'cronograma_pyp_seguimiento', 'cronograma_pyp_actividad', ['actividad_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_cronograma_pyp_actividad_mes', 'cronograma_pyp_seguimiento', ['actividad_id', 'mes'], postgresql_nulls_not_distinct=False)
    op.alter_column('cronograma_pyp_seguimiento', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('cronograma_pyp_seguimiento', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_constraint(None, 'cronograma_pyp_actividad', type_='foreignkey')
    op.create_foreign_key('cronograma_pyp_actividad_cronograma_id_fkey', 'cronograma_pyp_actividad', 'cronograma_pyp', ['cronograma_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cronograma_pyp_actividad', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('cronograma_pyp_actividad', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_constraint(None, 'cronograma_pyp', type_='foreignkey')
    op.create_foreign_key('cronograma_pyp_plan_trabajo_anual_id_fkey', 'cronograma_pyp', 'plan_trabajo_anual', ['plan_trabajo_anual_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cronograma_pyp', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('cronograma_pyp', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('criterios_exclusion', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###