"""Add programas table

Revision ID: 7a68cc80eff9
Revises: b03c6ded8553
Create Date: 2025-09-02 11:27:56.703356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a68cc80eff9'
down_revision = 'b03c6ded8553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create programas table
    op.create_table('programas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_programa', sa.String(length=200), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    
    # Create admin_config table
    op.create_table('admin_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('emo_periodicity', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_index(op.f('ix_admin_config_category'), 'admin_config', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_config_category'), table_name='admin_config')
    op.drop_index(op.f('ix_admin_config_id'), table_name='admin_config')
    op.drop_table('admin_config')
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    # ### end Alembic commands ###