"""Add eps_nombre, arl_nombre, afp_nombre fields to contractors table

Revision ID: 7f93cd8c9658
Revises: 561d98a9ea99
Create Date: 2025-10-03 22:18:38.278366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f93cd8c9658'
down_revision = '561d98a9ea99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contractor_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('contractor_contracts', 'contract_number')
    op.alter_column('contractor_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('contractor_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.add_column('contractors', sa.Column('eps_nombre', sa.String(length=100), nullable=True))
    op.add_column('contractors', sa.Column('afp_nombre', sa.String(length=100), nullable=True))
    op.add_column('contractors', sa.Column('arl_nombre', sa.String(length=100), nullable=True))
    op.alter_column('contractors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_contractors_document_number', table_name='contractors')
    op.create_index(op.f('ix_contractors_document_number'), 'contractors', ['document_number'], unique=True)
    op.drop_index('ix_contractors_email', table_name='contractors')
    op.create_index(op.f('ix_contractors_email'), 'contractors', ['email'], unique=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contractors_email'), table_name='contractors')
    op.create_index('ix_contractors_email', 'contractors', ['email'], unique=False)
    op.drop_index(op.f('ix_contractors_document_number'), table_name='contractors')
    op.create_index('ix_contractors_document_number', 'contractors', ['document_number'], unique=False)
    op.alter_column('contractors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_column('contractors', 'arl_nombre')
    op.drop_column('contractors', 'afp_nombre')
    op.drop_column('contractors', 'eps_nombre')
    op.alter_column('contractor_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('contractor_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.add_column('contractor_contracts', sa.Column('contract_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('contractor_contracts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###