"""Add second_name and second_last_name to contractors

Revision ID: 851cb97d4280
Revises: 7f93cd8c9658
Create Date: 2025-10-03 22:52:17.322016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851cb97d4280'
down_revision = '7f93cd8c9658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('second_name', sa.String(length=100), nullable=True))
    op.add_column('contractors', sa.Column('second_last_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'second_last_name')
    op.drop_column('contractors', 'second_name')
    # ### end Alembic commands ###