"""Add direccion column to workers table

Revision ID: 861b66515785
Revises: 37c7da4a4683
Create Date: 2025-09-03 19:57:12.242421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861b66515785'
down_revision = '37c7da4a4683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('direccion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'direccion')
    # ### end Alembic commands ###