"""add_worker_vacations_tables

Revision ID: 8daac6c61af5
Revises: b8520806b06a
Create Date: 2025-09-22 14:55:18.057137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daac6c61af5'
down_revision = 'b8520806b06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###