"""add_activo_to_criterios_exclusion

Revision ID: 9c1814cda1dc
Revises: 17c6dc093ad7
Create Date: 2026-01-27 22:31:36.579645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1814cda1dc'
down_revision = '17c6dc093ad7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criterios_exclusion', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('system_settings', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('criterios_exclusion', 'activo')
    # ### end Alembic commands ###