"""Renombrar valor de enum ENFERMEDAD LEVE a ENFERMEDAD_LEVE"""

from alembic import op
from sqlalchemy import text

# revision identifiers, generated by Alembic.
revision = 'a09d02d6b9c0'
down_revision = 'cf6a6f75b209'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    # Encontrar tipos enum que tengan el valor antiguo
    result = conn.execute(text("""
        SELECT DISTINCT t.typname
        FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        WHERE e.enumlabel = 'ENFERMEDAD LEVE'
    """))
    types = [row[0] for row in result]
    for typname in types:
        conn.execute(text("ALTER TYPE " + typname + " RENAME VALUE 'ENFERMEDAD LEVE' TO 'ENFERMEDAD_LEVE'"))

    # Si la columna fuese texto/varchar, normalizar datos con seguridad
    try:
        data_type = conn.execute(text("""
            SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'absenteeism' AND column_name = 'event_type'
        """)).scalar()
        if data_type and data_type.lower() in ('text', 'character varying', 'varchar'):
            conn.execute(text("""
                UPDATE absenteeism
                SET event_type = 'ENFERMEDAD_LEVE'
                WHERE event_type = 'ENFERMEDAD LEVE'
            """))
    except Exception:
        pass


def downgrade():
    conn = op.get_bind()
    result = conn.execute(text("""
        SELECT DISTINCT t.typname
        FROM pg_type t
        JOIN pg_enum e ON e.enumtypid = t.oid
        WHERE e.enumlabel = 'ENFERMEDAD_LEVE'
    """))
    types = [row[0] for row in result]
    for typname in types:
        conn.execute(text("ALTER TYPE " + typname + " RENAME VALUE 'ENFERMEDAD_LEVE' TO 'ENFERMEDAD LEVE'"))

    try:
        data_type = conn.execute(text("""
            SELECT data_type FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'absenteeism' AND column_name = 'event_type'
        """)).scalar()
        if data_type and data_type.lower() in ('text', 'character varying', 'varchar'):
            conn.execute(text("""
                UPDATE absenteeism
                SET event_type = 'ENFERMEDAD LEVE'
                WHERE event_type = 'ENFERMEDAD_LEVE'
            """))
    except Exception:
        pass
