"""create_seguridad_social_table

Revision ID: b75e3259670b
Revises: b57a123da9c2
Create Date: 2025-08-25 07:41:50.667430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b75e3259670b'
down_revision = 'b57a123da9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_config_category'), table_name='admin_config')
    op.drop_index(op.f('ix_admin_config_id'), table_name='admin_config')
    op.drop_table('admin_config')
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('programas_pkey'))
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    op.create_table('admin_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('emo_periodicity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_config_pkey'))
    )
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_index(op.f('ix_admin_config_category'), 'admin_config', ['category'], unique=False)
    # ### end Alembic commands ###