"""add_pdf_file_path_to_occupational_exams

Revision ID: b8520806b06a
Revises: 4491bdc63049
Create Date: 2025-09-22 01:01:08.197750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8520806b06a'
down_revision = '4491bdc63049'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_programas_id', table_name='programas')
    op.drop_table('programas')
    op.add_column('occupational_exams', sa.Column('pdf_file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupational_exams', 'pdf_file_path')
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='programas_pkey')
    )
    op.create_index('ix_programas_id', 'programas', ['id'], unique=False)
    # ### end Alembic commands ###