"""add_support_file_key_to_master_documents

Revision ID: bc7eeb3a5de3
Revises: 3af1edff4794
Create Date: 2026-02-24 23:42:59.544557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7eeb3a5de3'
down_revision = '3af1edff4794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_documents', sa.Column('support_file_key', sa.String(length=500), nullable=True))
    op.drop_column('occupational_exams', 'matrix_i_check')
    op.drop_column('occupational_exams', 'matrix_carta_check')
    op.drop_column('occupational_exams', 'matrix_seguimiento')
    op.drop_column('occupational_exams', 'matrix_p_check')
    op.drop_column('occupational_exams', 'matrix_plan_accion')
    op.drop_column('occupational_exams', 'matrix_e_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupational_exams', sa.Column('matrix_e_check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_plan_accion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_p_check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_seguimiento', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_carta_check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('occupational_exams', sa.Column('matrix_i_check', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('master_documents', 'support_file_key')
    # ### end Alembic commands ###