"""create homework_assessments table

Revision ID: c92a4567f855
Revises: 4c7c553077a2
Create Date: 2026-01-23 19:52:59.992000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92a4567f855'
down_revision = '4c7c553077a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('lighting_check', sa.Boolean(), nullable=True),
    sa.Column('lighting_obs', sa.Text(), nullable=True),
    sa.Column('ventilation_check', sa.Boolean(), nullable=True),
    sa.Column('ventilation_obs', sa.Text(), nullable=True),
    sa.Column('desk_check', sa.Boolean(), nullable=True),
    sa.Column('desk_obs', sa.Text(), nullable=True),
    sa.Column('chair_check', sa.Boolean(), nullable=True),
    sa.Column('chair_obs', sa.Text(), nullable=True),
    sa.Column('screen_check', sa.Boolean(), nullable=True),
    sa.Column('screen_obs', sa.Text(), nullable=True),
    sa.Column('mouse_keyboard_check', sa.Boolean(), nullable=True),
    sa.Column('mouse_keyboard_obs', sa.Text(), nullable=True),
    sa.Column('space_check', sa.Boolean(), nullable=True),
    sa.Column('space_obs', sa.Text(), nullable=True),
    sa.Column('floor_check', sa.Boolean(), nullable=True),
    sa.Column('floor_obs', sa.Text(), nullable=True),
    sa.Column('noise_check', sa.Boolean(), nullable=True),
    sa.Column('noise_obs', sa.Text(), nullable=True),
    sa.Column('connectivity_check', sa.Boolean(), nullable=True),
    sa.Column('connectivity_obs', sa.Text(), nullable=True),
    sa.Column('equipment_check', sa.Boolean(), nullable=True),
    sa.Column('equipment_obs', sa.Text(), nullable=True),
    sa.Column('confidentiality_check', sa.Boolean(), nullable=True),
    sa.Column('confidentiality_obs', sa.Text(), nullable=True),
    sa.Column('active_breaks_check', sa.Boolean(), nullable=True),
    sa.Column('active_breaks_obs', sa.Text(), nullable=True),
    sa.Column('psychosocial_check', sa.Boolean(), nullable=True),
    sa.Column('psychosocial_obs', sa.Text(), nullable=True),
    sa.Column('worker_signature', sa.String(length=255), nullable=True),
    sa.Column('sst_signature', sa.String(length=255), nullable=True),
    sa.Column('sst_observations', sa.Text(), nullable=True),
    sa.Column('home_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attachments_data', sa.Text(), nullable=True),
    sa.Column('photos_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_assessments_id'), 'homework_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_assessments_id'), table_name='homework_assessments')
    op.drop_table('homework_assessments')
    # ### end Alembic commands ###