"""Crear tabla seguimiento_actividades

Revision ID: cdbab7e8f7e8
Revises: be6c69421a9d
Create Date: 2025-09-21 22:58:19.842131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbab7e8f7e8'
down_revision = 'be6c69421a9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento_actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguimiento_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_fecha', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_unica', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_soporte_url', sa.String(length=500), nullable=True),
    sa.Column('archivo_soporte_nombre', sa.String(length=255), nullable=True),
    sa.Column('completada_por', sa.Integer(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['completada_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seguimiento_id'], ['seguimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimiento_actividades_id'), 'seguimiento_actividades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimiento_actividades_id'), table_name='seguimiento_actividades')
    op.drop_table('seguimiento_actividades')
    # ### end Alembic commands ###