"""remove_unnecessary_contractor_fields

Revision ID: cf6a6f75b209
Revises: 851cb97d4280
Create Date: 2025-10-03 23:01:10.274465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6a6f75b209'
down_revision = '851cb97d4280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'otros_documentos_url')
    op.drop_column('contractors', 'arl_nombre')
    op.drop_column('contractors', 'certificacion_arl_key')
    op.drop_column('contractors', 'eps_nombre')
    op.drop_column('contractors', 'otros_documentos_keys')
    op.drop_column('contractors', 'certificacion_arl_url')
    op.drop_column('contractors', 'certificacion_afp_url')
    op.drop_column('contractors', 'certificacion_eps_url')
    op.drop_column('contractors', 'certificacion_afp_key')
    op.drop_column('contractors', 'certificacion_eps_key')
    op.drop_column('contractors', 'afp_nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('afp_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_eps_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_afp_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_eps_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_afp_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_arl_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('otros_documentos_keys', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('eps_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('certificacion_arl_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('arl_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contractors', sa.Column('otros_documentos_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###