"""Make diagnostic_code and health_condition_description nullable for ENFERMEDAD_LEVE

Revision ID: df58e15de5f6
Revises: 068250d6256f
Create Date: 2025-09-25 18:57:08.236024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df58e15de5f6'
down_revision = '068250d6256f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('absenteeism', 'diagnostic_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('absenteeism', 'health_condition_description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('absenteeism', 'health_condition_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('absenteeism', 'diagnostic_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###