"""add_virtual_attendance_fields

Revision ID: e41d5baf35e2
Revises: 2b0c3dbbc4e8
Create Date: 2025-11-01 19:04:02.009054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e41d5baf35e2'
down_revision = '2b0c3dbbc4e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_programas_id', table_name='programas')
    op.drop_table('programas')
    op.add_column('attendances', sa.Column('session_code', sa.String(length=20), nullable=True))
    op.add_column('attendances', sa.Column('session_code_used_at', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('virtual_session_link', sa.String(length=500), nullable=True))
    op.add_column('attendances', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('attendances', sa.Column('connection_quality', sa.String(length=50), nullable=True))
    op.add_column('attendances', sa.Column('minimum_duration_met', sa.Boolean(), nullable=True))
    op.add_column('attendances', sa.Column('facilitator_confirmed', sa.Boolean(), nullable=True))
    op.add_column('attendances', sa.Column('virtual_evidence', sa.Text(), nullable=True))
    op.add_column('attendances', sa.Column('browser_info', sa.String(length=255), nullable=True))
    op.alter_column('occupational_exams', 'requires_follow_up',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('occupational_exams', 'requires_follow_up',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('attendances', 'browser_info')
    op.drop_column('attendances', 'virtual_evidence')
    op.drop_column('attendances', 'facilitator_confirmed')
    op.drop_column('attendances', 'minimum_duration_met')
    op.drop_column('attendances', 'connection_quality')
    op.drop_column('attendances', 'device_fingerprint')
    op.drop_column('attendances', 'virtual_session_link')
    op.drop_column('attendances', 'session_code_used_at')
    op.drop_column('attendances', 'session_code')
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='programas_pkey')
    )
    op.create_index('ix_programas_id', 'programas', ['id'], unique=False)
    # ### end Alembic commands ###