"""Add VirtualSession table

Revision ID: e49f5c85d29b
Revises: e41d5baf35e2
Create Date: 2025-11-01 21:06:11.766624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49f5c85d29b'
down_revision = 'e41d5baf35e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('virtual_session_link', sa.String(length=500), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_code')
    )
    op.create_index(op.f('ix_virtual_sessions_id'), 'virtual_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_sessions_id'), table_name='virtual_sessions')
    op.drop_table('virtual_sessions')
    # ### end Alembic commands ###