"""create_committees_tables

Revision ID: ed563185f685
Revises: 5c65bc7039ff
Create Date: 2025-09-23 22:44:55.375423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed563185f685'
down_revision = '5c65bc7039ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_committee_roles_id'), 'committee_roles', ['id'], unique=False)
    op.create_table('committee_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_committee_types_id'), 'committee_types', ['id'], unique=False)
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.Enum('COPASST', 'CONVIVENCIA', name='committeetypeenum'), nullable=False),
    sa.Column('committee_type_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('dissolution_date', sa.Date(), nullable=True),
    sa.Column('meeting_frequency_days', sa.Integer(), nullable=True),
    sa.Column('quorum_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('regulations_document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('dissolution_date IS NULL OR establishment_date IS NULL OR dissolution_date >= establishment_date', name='check_dissolution_after_establishment'),
    sa.CheckConstraint('meeting_frequency_days > 0', name='check_meeting_frequency'),
    sa.CheckConstraint('quorum_percentage >= 0 AND quorum_percentage <= 100', name='check_quorum_percentage'),
    sa.ForeignKeyConstraint(['committee_type_id'], ['committee_types.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_type_active', 'committees', ['committee_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)
    op.create_table('committee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('MEETING_MINUTES', 'REGULATION', 'REPORT', 'INVESTIGATION', 'PROCEDURE', 'FORM', 'CERTIFICATE', 'OTHER', name='documenttypeenum'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('download_count >= 0', name='check_non_negative_downloads'),
    sa.CheckConstraint('file_size IS NULL OR file_size > 0', name='check_positive_file_size'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_document_type', 'committee_documents', ['committee_id', 'document_type'], unique=False)
    op.create_index('idx_document_public', 'committee_documents', ['is_public'], unique=False)
    op.create_index(op.f('ix_committee_documents_id'), 'committee_documents', ['id'], unique=False)
    op.create_table('committee_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'POSTPONED', name='meetingstatusenum'), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('minutes_content', sa.Text(), nullable=True),
    sa.Column('minutes_document_url', sa.String(length=500), nullable=True),
    sa.Column('quorum_achieved', sa.Boolean(), nullable=True),
    sa.Column('attendees_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('attendees_count >= 0', name='check_non_negative_attendees'),
    sa.CheckConstraint('duration_minutes > 0', name='check_positive_duration'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_meeting_date', 'committee_meetings', ['committee_id', 'meeting_date'], unique=False)
    op.create_index('idx_meeting_status', 'committee_meetings', ['status'], unique=False)
    op.create_index(op.f('ix_committee_meetings_id'), 'committee_meetings', ['id'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PRESIDENT', 'VICE_PRESIDENT', 'SECRETARY', 'MEMBER', 'ALTERNATE', name='committeeroleenum'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('appointment_document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='check_end_after_start'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['committee_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_role', 'committee_members', ['committee_id', 'role'], unique=False)
    op.create_index('idx_committee_user_active', 'committee_members', ['committee_id', 'user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)
    op.create_table('committee_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_type', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > granted_at', name='check_expiry_after_granted'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_user_permission', 'committee_permissions', ['committee_id', 'user_id', 'permission_type'], unique=False)
    op.create_index('idx_permission_active', 'committee_permissions', ['is_active'], unique=False)
    op.create_index(op.f('ix_committee_permissions_id'), 'committee_permissions', ['id'], unique=False)
    op.create_table('committee_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='activitypriorityenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='activitystatusenum'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('supporting_document_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('completion_date IS NULL OR due_date IS NULL OR completion_date >= due_date', name='check_completion_after_due'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='check_progress_percentage'),
    sa.ForeignKeyConstraint(['assigned_to'], ['committee_members.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_assigned_to', 'committee_activities', ['assigned_to'], unique=False)
    op.create_index('idx_activity_due_date', 'committee_activities', ['due_date'], unique=False)
    op.create_index('idx_committee_activity_status', 'committee_activities', ['committee_id', 'status'], unique=False)
    op.create_index(op.f('ix_committee_activities_id'), 'committee_activities', ['id'], unique=False)
    op.create_table('committee_votings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voting_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='votingstatusenum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('requires_quorum', sa.Boolean(), nullable=False),
    sa.Column('minimum_votes_required', sa.Integer(), nullable=True),
    sa.Column('allow_abstention', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='check_end_after_start_voting'),
    sa.CheckConstraint('minimum_votes_required IS NULL OR minimum_votes_required > 0', name='check_positive_minimum_votes'),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_committee_voting_status', 'committee_votings', ['committee_id', 'status'], unique=False)
    op.create_index('idx_voting_dates', 'committee_votings', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_committee_votings_id'), 'committee_votings', ['id'], unique=False)
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', 'LATE', name='attendancestatusenum'), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('excuse_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('departure_time IS NULL OR arrival_time IS NULL OR departure_time >= arrival_time', name='check_departure_after_arrival'),
    sa.ForeignKeyConstraint(['meeting_id'], ['committee_meetings.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['committee_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meeting_member_attendance', 'meeting_attendance', ['meeting_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendance_id'), 'meeting_attendance', ['id'], unique=False)
    op.create_table('committee_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('vote_choice', sa.Enum('YES', 'NO', 'ABSTAIN', name='votechoiceenum'), nullable=False),
    sa.Column('vote_date', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_proxy_vote', sa.Boolean(), nullable=False),
    sa.Column('proxy_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['committee_members.id'], ),
    sa.ForeignKeyConstraint(['proxy_member_id'], ['committee_members.id'], ),
    sa.ForeignKeyConstraint(['voting_id'], ['committee_votings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voting_member_vote', 'committee_votes', ['voting_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_committee_votes_id'), 'committee_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_committee_votes_id'), table_name='committee_votes')
    op.drop_index('idx_voting_member_vote', table_name='committee_votes')
    op.drop_table('committee_votes')
    op.drop_index(op.f('ix_meeting_attendance_id'), table_name='meeting_attendance')
    op.drop_index('idx_meeting_member_attendance', table_name='meeting_attendance')
    op.drop_table('meeting_attendance')
    op.drop_index(op.f('ix_committee_votings_id'), table_name='committee_votings')
    op.drop_index('idx_voting_dates', table_name='committee_votings')
    op.drop_index('idx_committee_voting_status', table_name='committee_votings')
    op.drop_table('committee_votings')
    op.drop_index(op.f('ix_committee_activities_id'), table_name='committee_activities')
    op.drop_index('idx_committee_activity_status', table_name='committee_activities')
    op.drop_index('idx_activity_due_date', table_name='committee_activities')
    op.drop_index('idx_activity_assigned_to', table_name='committee_activities')
    op.drop_table('committee_activities')
    op.drop_index(op.f('ix_committee_permissions_id'), table_name='committee_permissions')
    op.drop_index('idx_permission_active', table_name='committee_permissions')
    op.drop_index('idx_committee_user_permission', table_name='committee_permissions')
    op.drop_table('committee_permissions')
    op.drop_index(op.f('ix_committee_members_id'), table_name='committee_members')
    op.drop_index('idx_committee_user_active', table_name='committee_members')
    op.drop_index('idx_committee_role', table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_committee_meetings_id'), table_name='committee_meetings')
    op.drop_index('idx_meeting_status', table_name='committee_meetings')
    op.drop_index('idx_committee_meeting_date', table_name='committee_meetings')
    op.drop_table('committee_meetings')
    op.drop_index(op.f('ix_committee_documents_id'), table_name='committee_documents')
    op.drop_index('idx_document_public', table_name='committee_documents')
    op.drop_index('idx_committee_document_type', table_name='committee_documents')
    op.drop_table('committee_documents')
    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_index('idx_committee_type_active', table_name='committees')
    op.drop_table('committees')
    op.drop_index(op.f('ix_committee_types_id'), table_name='committee_types')
    op.drop_table('committee_types')
    op.drop_index(op.f('ix_committee_roles_id'), table_name='committee_roles')
    op.drop_table('committee_roles')
    # ### end Alembic commands ###