"""add_notification_acknowledgment_table

Revision ID: fe52450538d1
Revises: 7a68cc80eff9
Create Date: 2025-09-03 11:32:56.412530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe52450538d1'
down_revision = '7a68cc80eff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('occupational_exam_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('stops_notifications', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['occupational_exam_id'], ['occupational_exams.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_acknowledgments_id'), 'notification_acknowledgments', ['id'], unique=False)
    op.drop_index(op.f('ix_admin_config_category'), table_name='admin_config')
    op.drop_index(op.f('ix_admin_config_id'), table_name='admin_config')
    op.drop_table('admin_config')
    op.drop_index(op.f('ix_programas_id'), table_name='programas')
    op.drop_table('programas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_programa', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('programas_pkey'))
    )
    op.create_index(op.f('ix_programas_id'), 'programas', ['id'], unique=False)
    op.create_table('admin_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('emo_periodicity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_config_pkey'))
    )
    op.create_index(op.f('ix_admin_config_id'), 'admin_config', ['id'], unique=False)
    op.create_index(op.f('ix_admin_config_category'), 'admin_config', ['category'], unique=False)
    op.drop_index(op.f('ix_notification_acknowledgments_id'), table_name='notification_acknowledgments')
    op.drop_table('notification_acknowledgments')
    # ### end Alembic commands ###