"""remove username field

Revision ID: remove_username_001
Revises: 34a1a8c64483
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_username_001'
down_revision = '34a1a8c64483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique index on username first
    op.drop_index('ix_users_username', table_name='users')
    # Drop the username column
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the username column back
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # Recreate the unique index
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###